variables:
  DOCKER_DRIVER: overlay2
  HTTPD24_BASE_IMAGE: httpd:2.4.43-alpine

stages:
  - build

.build: &build
  only:
    - tags
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"${DOCKERHUB_REGISTRY}\":{\"username\":\"${DOCKERHUB_USER}\",\"password\":\"${DOCKERHUB_TOKEN}\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --build-arg BUILD_HTTPD_IMAGE --context ${CI_PROJECT_DIR} --destination ${DOCKERHUB_IMAGE_PATH}:${BUILD_HTTPD_VERSION}-${CI_COMMIT_TAG} --dockerfile ${CI_PROJECT_DIR}/Dockerfile

build:2.4:
  <<: *build
  variables:
    BUILD_HTTPD_IMAGE: ${HTTPD24_BASE_IMAGE}
    BUILD_HTTPD_VERSION: '2.4'
