name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - httpd-version: 2.4
            httpd-image: httpd:2.4.52-alpine
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build ${{ matrix.httpd-version }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_HTTPD_IMAGE=${{ matrix.httpd-image }}
          push: true
          tags: aerzas/httpd:${{ matrix.httpd-version }}-latest,aerzas/httpd:${{ matrix.httpd-version }}-${{ github.ref_name }}
